"""module3_oauth_columns

Revision ID: d39e30e14184
Revises: 0001_initial
Create Date: 2026-08-08 06:13:13.134654+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'd39e30e14184'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarked_problems',
    sa.Column('bookmark_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_priority', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.problem_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bookmark_id'),
    sa.UniqueConstraint('user_id', 'problem_id', name='uq_bookmark_user_problem')
    )
    op.create_index(op.f('ix_bookmarked_problems_bookmark_id'), 'bookmarked_problems', ['bookmark_id'], unique=False)
    op.create_index(op.f('ix_bookmarked_problems_problem_id'), 'bookmarked_problems', ['problem_id'], unique=False)
    op.create_index(op.f('ix_bookmarked_problems_user_id'), 'bookmarked_problems', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('profile_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_solved', sa.Integer(), nullable=False),
    sa.Column('total_submissions', sa.Integer(), nullable=False),
    sa.Column('acceptance_rate', sa.Float(), nullable=False),
    sa.Column('easy_solved', sa.Integer(), nullable=False),
    sa.Column('medium_solved', sa.Integer(), nullable=False),
    sa.Column('hard_solved', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index(op.f('ix_user_profiles_profile_id'), 'user_profiles', ['profile_id'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.drop_index(op.f('ix_hints_hint_embedding_hnsw'), table_name='knowledge_base_hints', postgresql_ops={'hint_embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.execute("ALTER TABLE knowledge_base_hints ALTER COLUMN hint_embedding TYPE VECTOR(384) USING NULL;")
    op.drop_index(op.f('ix_problems_problem_embedding_hnsw'), table_name='problems', postgresql_ops={'problem_embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.execute("ALTER TABLE problems ALTER COLUMN problem_embedding TYPE VECTOR(384) USING NULL;")
    op.drop_index(op.f('ix_submissions_code_embedding_hnsw'), table_name='submissions', postgresql_ops={'code_embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.execute("ALTER TABLE submissions ALTER COLUMN code_embedding TYPE VECTOR(384) USING NULL;")
    op.add_column('users', sa.Column('oauth_provider', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('oauth_id', sa.String(length=256), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.create_index(op.f('ix_users_oauth_id'), 'users', ['oauth_id'], unique=False)
    op.create_index(op.f('ix_users_oauth_provider'), 'users', ['oauth_provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_oauth_provider'), table_name='users')
    op.drop_index(op.f('ix_users_oauth_id'), table_name='users')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.drop_column('users', 'oauth_id')
    op.drop_column('users', 'oauth_provider')
    op.create_index(op.f('ix_submissions_code_embedding_hnsw'), 'submissions', ['code_embedding'], unique=False, postgresql_ops={'code_embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.alter_column('submissions', 'code_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)
    op.create_index(op.f('ix_problems_problem_embedding_hnsw'), 'problems', ['problem_embedding'], unique=False, postgresql_ops={'problem_embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.alter_column('problems', 'problem_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)
    op.create_index(op.f('ix_hints_hint_embedding_hnsw'), 'knowledge_base_hints', ['hint_embedding'], unique=False, postgresql_ops={'hint_embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.alter_column('knowledge_base_hints', 'hint_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_profile_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_bookmarked_problems_user_id'), table_name='bookmarked_problems')
    op.drop_index(op.f('ix_bookmarked_problems_problem_id'), table_name='bookmarked_problems')
    op.drop_index(op.f('ix_bookmarked_problems_bookmark_id'), table_name='bookmarked_problems')
    op.drop_table('bookmarked_problems')
    # ### end Alembic commands ###
